### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yijunyu** [trusted-programming/rust-diagnostics#1]
# Tasks

### Diagnostics
- [x] Insert two comments around the diagnositic spans
- [x] Name the comments by the lint rules, and insert the rendered diagnostics into the second comment
- [x] Insert rendered diagnostic messages into the second comment.

### Configuration
- [x] Add an option '--fix' to invoke flags related to all machine applicable fix rules from rust-clippy project

### Measurement
- [x] Measure the number of warnings per KLOC through `count_diagnostics.sh`
- [x] Count clippy fixes

### Git History Extraction
- [x] Select only the relevant marked rules
- [x] Print out the hunks only when they are relevant to the spans of warning locations
- [x] Output options
  - [x] Add an option `--patch <id>` to print out the patch of HEAD..<id> where <id> is a commit id and HEAD is the current work tree
  - [x] Add an option `--commit` to print out the hunks only when they have been fixed by the revision <id>
  - [x] Add an option `--pair` to generate diff records into code pairs
  - [x] Add an option `--function` to generate diff records with the surrounding function contexts (which was a feature of `git diff` but not supported by `libgit2`
  - [x] Add an option `--single` to select only those diff records that patch exactly one warning
  - [x] Add an option `--mixed` to save the messages into a file in case the information can be useful context
  - [x] Add an option `--location` to markup the old_context with the warnings

### Refactoring
- [ ] Integrate with transformation systems to fix some of the warnings not yet fixed by clippy
   - [x] Integrate with `txl` through `txl-rs`
   - [x] list the marked rules applied to the transformations
   - [x] Updated the TXL refactoring transformation and Rust grammar
   - [ ] List the fixed warnings and keep the remaining warnings in the output
   - [ ] Store the transformation results before and after `clippy --fix` into the `transform` folder 
   - [ ] Call fix only when the number of warnings is larger than 0
   - [ ] Perform `rustfmt` to output of TXL transformations
- [ ] Infer return type of functions and map them to if-let test: Result => Ok(), Option => Some()

## Usability

- [x] Separate the output files into a different folder, so as to keep using the same ".rs" file extension
- [x] Save the messages into `[$hash]/diagnostics.json` to avoid rerun the compilation for changes of the tool features
      where $hash is the hash id of the current work copy of a git repository
- [x] Swap the order of diagnostic folder name from `$id/diagnostics` to `diagnostics/$id`
- [x] Cache computed data by serialized/deserialize diff hunks
- [x] Put header ahead of before and after contexts of the hunk pairs
- [x] Print pair pragma with ## so it is easier to differentiate it with the pragma inside warning hints

## Testing
- [x] Test rust-diagnostics on its own history
- [x] Generate test results in random folders so there is less interference between tests
- [x] Fix the ordering of diagnostic hints so that the regression test will be repeatable 
- [ ] Make the test cases parallelizable

## Maintainability
- [x] Move the implementation of optional functionalities into rustc_flags, fix features to reduce the dependencies
- [x] Refactor the code to simplify the logic by introduce a Hunk structure as unified state of various analyses
- [x] Removed the optional features
- [x] Remove dependencies requiring nightly, now only depends on stable rust
- [x] Use cargo-release and cargo-dist to create the new release
